Green_Lagoon/ViewModels/VillaAmenitiesViewModel.cs
using Green_Lagoon.Domain.Entities;
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Green_Lagoon.ViewModels
{
    public class VillaAmenitiesViewModel
    {
        public Amenity Amenity { get; set; }
        [ValidateNever]
        public IEnumerable<SelectListItem> VillaList { get; set; }
    }
}

Green_Lagoon/Controllers/VillaAmenityController.cs
using Green_Lagoon.Application.Common.Interface;
using Green_Lagoon.Application.Common.Utility;
using Green_Lagoon.Domain.Entities;
using Green_Lagoon.Infrastructure.Data;
using Green_Lagoon.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Green_Lagoon.Controllers
{
    [Authorize(Roles =SD.Role_Admin)]
    public class VillaAmenityController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public VillaAmenityController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            var villaNumbers = _unitOfWork.Amenity.GetAll(includeProperties: "Villa");
            return View(villaNumbers);
        }
        public IActionResult Create()
        {
            VillaAmenitiesViewModel Amenity = new()
            {
                VillaList = _unitOfWork.Villa.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString(),
                })
            };


            return View(Amenity);
        }
        [HttpPost]
        public IActionResult Create(VillaAmenitiesViewModel obj)
        {
           

            if (ModelState.IsValid )
            {
                
                _unitOfWork.Amenity.Add(obj.Amenity);
                _unitOfWork.Save();
                TempData["success"] = "The Villa Amenity has been created successfully.";
                return RedirectToAction(nameof(Index));
            }
           
            obj.VillaList = _unitOfWork.Villa.GetAll().Select(u => new SelectListItem
            {
                Text = u.Name,
                Value = u.Id.ToString(),
            });
            return View(obj);

        }
        [HttpGet]
        public IActionResult Update(int Id)
        {
            VillaAmenitiesViewModel amenity = new()
            {
                VillaList = _unitOfWork.Villa.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString(),
                }),
                Amenity = _unitOfWork.Amenity.Get(u => u.Id == Id )
            };

            if (amenity.Amenity == null)
            {
                return RedirectToAction("Error", "Home");
            }
            return View(amenity);
        }
        [HttpPost]
        public IActionResult Update(VillaAmenitiesViewModel villaAmenityViewModel)
        {


            ModelState.Remove("VillaList");
            if (ModelState.IsValid)
            {
                _unitOfWork.Amenity.Update(villaAmenityViewModel.Amenity);
                _unitOfWork.Save();
                TempData["success"] = "The Villa Amenity has been updated successfully.";
                return RedirectToAction(nameof(Index));
            }


            villaAmenityViewModel.VillaList = _unitOfWork.Villa.GetAll().Select(u => new SelectListItem
            {
                Text = u.Name,
                Value = u.Id.ToString(),
            });
            return View(villaAmenityViewModel);

        }
        [HttpGet]
        public IActionResult Delete(int Id)
        {
            VillaAmenitiesViewModel amenities = new()
            {
                VillaList = _unitOfWork.Villa.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString(),
                }),
                Amenity = _unitOfWork.Amenity.Get(u => u.Id == Id)
            };

            if (amenities.Amenity == null)
            {
                return RedirectToAction("Error", "Home");
            }
            return View(amenities);
        }
        [HttpPost]
        public IActionResult Delete(VillaAmenitiesViewModel villaamenitiesViewModel)
        {
            Amenity? objfromDb = _unitOfWork.Amenity.Get(x => x.Id == villaamenitiesViewModel.Amenity.Id);
            if (objfromDb is not null)
            {
                _unitOfWork.Amenity.Remove(objfromDb);
                _unitOfWork.Save();
                TempData["success"] = "The Villa Amenity has been deleted successfully.";
                return RedirectToAction(nameof(Index));

            }
            TempData["error"] = "The Villa Amenity can not be deleted.";

            return View();

        }

    }
}

Green_Lagoon/Views/VillaAmenity/Create.cshtml
@model VillaAmenitiesViewModel

<div class="w-100 card border-0">
    <div class="card-header bg-success bg-gradient m-lg-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h1 class="text-white py-2">Create Villa Number</h1>
            </div>
        </div>
    </div>
</div>
<div class="card-body border-4">
    <form method="post" class="row">
        <div class="p-3">
            @*  <div asp-validation-summary="ModelOnly"></div> *@
            <div class="form-floating py-2 col-12">
                <select asp-for="@Model.Amenity.VillaId" asp-items="@Model.VillaList" class="form-select border shadow">
                    <option disabled selected>--Select Villa--</option>
                </select>
                <label asp-for="Amenity.VillaId" class="ms-2"></label>

            </div>
            <div class="form-floating py-2 col-12">
                <input asp-for="@Model.Amenity.Name" class="form-control border shadow" />
                <label asp-for="Amenity.Name" class="ms-2"></label>

            </div>
            <div class="form-floating py-2 col-12">
                <input asp-for="@Model.Amenity.Description" class="form-control border shadow" />
                <label asp-for="Amenity.Description" class="ms-2"></label>

            </div>
            <div class="row pt-2">
                <div class="col-6 col-md-3">
                    <button type="submit" class="btn btn-success w-100">
                        <i class="bi bi-check-circle"> Create</i>
                    </button>
                </div>
                <div class="col-6 col-md-3">
                    <a asp-controller="VillaAmenity" asp-action="Index" class="btn btn-secondary w-100">
                        <i class="bi bi-x-circle"> Cancel</i>
                    </a>
                </div>
            </div>
        </div>
    </form>

</div>

@* @section Scripts{
    @{
        <partial name="_ValidationScripsPartial" />
    }
} *@

Green_Lagoon/Views/VillaAmenity/Delete.cshtml
@model VillaAmenitiesViewModel

<div class="w-100 card border-0">
    <div class="card-header bg-success bg-gradient m-lg-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h1 class="text-white py-2">Delet Villa Amenity</h1>
            </div>
        </div>
    </div>
</div>
<div class="card-body border-4">
    <form method="post" class="row">

        <input asp-for="Amenity.Id" hidden />
        <div class="p-3">

            <div class="form-floating py-2 col-12">
                <select asp-for="@Model.Amenity.VillaId" disabled asp-items="@Model.VillaList" class="form-select border shadow">
                    <option disabled selected>--Select Villa--</option>
                </select>
                <label asp-for="Amenity.VillaId" class="ms-2"></label>

            </div>
            <div class="form-floating py-2 col-12">
                <input asp-for="@Model.Amenity.Name" readonly class="form-control border shadow" />
                <label asp-for="Amenity.Name" class="ms-2"></label>

            </div>
            <div class="form-floating py-2 col-12">
                <input asp-for="@Model.Amenity.Description" readonly class="form-control border shadow" />
                <label asp-for="Amenity.Description" class="ms-2"></label>

            </div>
            <div class="row pt-2">
                <div class="col-6 col-md-3">
                    <button type="submit" class="btn btn-danger w-100">
                        <i class="bi bi-check-circle"> Delete</i>
                    </button>
                </div>
                <div class="col-6 col-md-3">
                    <a asp-controller="VillaAmenity" asp-action="Index" class="btn btn-secondary w-100">
                        <i class="bi bi-x-circle"> Cancel</i>
                    </a>
                </div>
            </div>
        </div>
    </form>

</div>

@* @section Scripts{
    @{
        <partial name="_ValidationScripsPartial" />
    }
} *@

Green_Lagoon/Views/VillaAmenity/Index.cshtml
@model IEnumerable<Amenity>

<div class="w-100 card border-0">
    <div class="card-header bg-success bg-gradient m-lg-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h1 class="text-white py-2">Villa Amenities List</h1>
            </div>
        </div>
    </div>
    <div class="card-body border p-4">
        <div class="row pb-3">
            <div class="col-6 offset-6 text-end">
                <a asp-controller="VillaAmenity" asp-action="Create" class="btn btn-secondary">
                    <i class="bi bi-plus-circle"></i> Create New Villa Amenity
                </a>
            </div>
        </div>
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>
                        Id
                    </th>
                    <th>
                        Name
                    </th>
                    <th>
                       Villa
                    </th>

                    <th>

                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var obj in Model)
                {
                    <tr>
                        <td>
                            @obj.Id
                        </td>
                        <td>
                            @obj.Name
                        </td>
                        <td>
                            @obj.Villa.Name
                        </td>

                        <td>
                            <div class="w-75 btn-group" role="group">
                                <a asp-controller="VillaAmenity" asp-action="Update" asp-route-Id="@obj.Id" class="btn btn-success mx-2">
                                    <i class="bi bi-pencil-square">Edit</i>
                                </a>
                                <a asp-controller="VillaAmenity" asp-action="Delete" asp-route-Id="@obj.Id" class="btn btn-danger mx-2">
                                    <i class="bi bi-trash-fill">Delete</i>
                                </a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

Green_Lagoon/Views/VillaAmenity/Update.cshtml
@model VillaAmenitiesViewModel

<div class="w-100 card border-0">
    <div class="card-header bg-success bg-gradient m-lg-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h1 class="text-white py-2">Update Villa Number</h1>
            </div>
        </div>
    </div>
</div>
<div class="card-body border-4">
    <form method="post" class="row">

        <input asp-for="Amenity.Id" hidden />
        <div class="p-3">

            <div class="form-floating py-2 col-12">
                <select asp-for="@Model.Amenity.VillaId" asp-items="@Model.VillaList" class="form-select border shadow">
                    <option disabled selected>--Select Villa--</option>
                </select>
                <label asp-for="Amenity.VillaId" class="ms-2"></label>

            </div>
            <div class="form-floating py-2 col-12">
                <input asp-for="@Model.Amenity.Name"  class="form-control border shadow" />
                <label asp-for="Amenity.Name" class="ms-2"></label>

            </div>
            <div class="form-floating py-2 col-12">
                <input asp-for="@Model.Amenity.Description" class="form-control border shadow" />
                <label asp-for="Amenity.Description" class="ms-2"></label>

            </div>
            <div class="row pt-2">
                <div class="col-6 col-md-3">
                    <button type="submit" class="btn btn-success w-100">
                        <i class="bi bi-check-circle"> Update</i>
                    </button>
                </div>
                <div class="col-6 col-md-3">
                    <a asp-controller="VillaAmenity" asp-action="Index" class="btn btn-secondary w-100">
                        <i class="bi bi-x-circle"> Cancel</i>
                    </a>
                </div>
            </div>
        </div>
    </form>

</div>

@* @section Scripts{
    @{
        <partial name="_ValidationScripsPartial" />
    }
} *@