Green_Lagoon/Controllers/BookingController.cs
using Green_Lagoon.Application.Common.Interface;
using Green_Lagoon.Application.Common.Utility;
using Green_Lagoon.Domain.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Stripe;
using Stripe.Checkout;
using System.Security.Claims;

namespace Green_Lagoon.Controllers
{
    public class BookingController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public BookingController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        [Authorize]
        public IActionResult Index()
        {
            return View();
        }
        [Authorize]
        public IActionResult FinalizeBooking(int villaId, DateOnly CheckInDate, int nights)
        {
            var claimsIdentity=(ClaimsIdentity)User.Identity;
            var userId=claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;

            ApplicationUser user=_unitOfWork.User.Get(u=>u.Id==userId);
            Booking booking = new()
            {
                VillaId = villaId,
                Villa = _unitOfWork.Villa.Get(u => u.Id == villaId, includeProperties: "VillaAmenity"),
                CheckInDate = CheckInDate,
                Nights = nights,
                CheckInOut= CheckInDate.AddDays(nights),
                UserId = userId,
                Phone=user.PhoneNumber,
                Email=user.Email,
                Name=user.Name,
                
            };
            booking.TotalCost = booking.Villa.Price * nights;
            return View(booking);
        }
        [Authorize]
        [HttpPost]
        public IActionResult FinalizeBooking(Booking booking)
        {
            var villa = _unitOfWork.Villa.Get(u => u.Id == booking.VillaId);
            booking.TotalCost = villa.Price * booking.Nights;

            booking.Status = SD.StatusPending;
            booking.BookingDate= DateTime.Now;

            var villaNumbersList = _unitOfWork.VillaNumber.GetAll().ToList();
            var bookedVillas = _unitOfWork.Booking.GetAll(u => u.Status == SD.StatusApproved || u.Status == SD.StatusCheckedIn).ToList();
           
                int roomsAvailable = SD.VillaRoomAvailable_Count(villa.Id, villaNumbersList, booking.CheckInDate, booking.Nights, bookedVillas);

            if (roomsAvailable == 0)
            {
                TempData["error"] = "Rooms fully booked";
                return RedirectToAction(nameof(FinalizeBooking), new
                {
                    villaId = booking.VillaId,
                    checkinInDate = booking.CheckInDate,
                    nights = booking.Nights,
                });
            }
            


            _unitOfWork.Booking.Add(booking);
            _unitOfWork.Save();
            var domain = Request.Scheme+ "://"+Request.Host.Value+"/";
            var options = new SessionCreateOptions
            {
                LineItems = new List<SessionLineItemOptions>(),
                Mode = "payment",
                SuccessUrl = domain + $"booking/BookingConfirmation?bookingId={booking.Id}",
                CancelUrl = domain + $"booking/FinalizeBooking?villaId={booking.VillaId}&CheckInDate={booking.CheckInDate}$nights={booking.Nights}",
            };


            options.LineItems.Add(new SessionLineItemOptions
            {
                PriceData = new SessionLineItemPriceDataOptions
                {
                    UnitAmount = (long)(booking.TotalCost * 100),
                    Currency = "usd",
                    ProductData = new SessionLineItemPriceDataProductDataOptions
                    {
                        Name = villa.Name,
                        //Images= new List<string> {domain +villa.ImageUrl}
                    },
                },
                Quantity=1,
            });
                
          
            var service = new SessionService();
            Session session = service.Create(options);
            _unitOfWork.Booking.UpdateStripePaymentID(booking.Id, session.Id, session.PaymentIntentId);
            _unitOfWork.Save();

            Response.Headers.Add("Location", session.Url);
            return new StatusCodeResult(303);
           
        }
        
        [Authorize]
        public IActionResult BookingConfirmation(int bookingId)
        {
            Booking bookingFromDb=_unitOfWork.Booking.Get(u=>u.Id==bookingId,includeProperties: "User,Villa");
            if(bookingFromDb.Status==SD.StatusPending)
            {
                var service= new SessionService();
                Session session = service.Get(bookingFromDb.StripeSessionId);

                if(session.PaymentStatus=="paid")
                {
                    _unitOfWork.Booking.UpdateStatus(bookingFromDb.Id, SD.StatusApproved,0);
                    _unitOfWork.Booking.UpdateStripePaymentID(bookingFromDb.Id, session.Id, session.PaymentIntentId);
                    _unitOfWork.Save();
                }
            }
            return View();
        }
        [Authorize]
        public IActionResult BookingDetails(int bookingId)
        {
            Booking bookingFromDb = _unitOfWork.Booking.Get(u => u.Id == bookingId, includeProperties: "User,Villa");

            if(bookingFromDb.VillaNumber==0 && bookingFromDb.Status==SD.StatusApproved)
            {
                var availableVillaNumber = AssignAvailableVillaNumberByVilla(bookingFromDb.VillaId);

                bookingFromDb.VillaNumbers = _unitOfWork.VillaNumber.GetAll(u => u.VillaId == bookingFromDb.VillaId && availableVillaNumber.Any(x => x == u.Villa_Number)).ToList();
            }
            return View(bookingFromDb);
        }
        [HttpPost]
        [Authorize(Roles =SD.Role_Admin)]

        public IActionResult CheckIn(Booking booking)
        {
            _unitOfWork.Booking.UpdateStatus(booking.Id, SD.StatusCheckedIn, booking.VillaNumber);
            _unitOfWork.Save();
            TempData["Success"] = "Booking updated Successfull";
            return RedirectToAction(nameof(BookingDetails), new {bookingId=booking.Id});
        }
        [HttpPost]
        [Authorize(Roles = SD.Role_Admin)]

        public IActionResult CheckOut(Booking booking)
        {
            _unitOfWork.Booking.UpdateStatus(booking.Id, SD.StatusCompleted, booking.VillaNumber);
            _unitOfWork.Save();
            TempData["Success"] = "Booking coompleted Successfull";
            return RedirectToAction(nameof(BookingDetails), new { bookingId = booking.Id });
        }
        [HttpPost]
        [Authorize(Roles = SD.Role_Admin)]

        public IActionResult CancelBooking(Booking booking)
        {
            _unitOfWork.Booking.UpdateStatus(booking.Id, SD.StatusCancelled, 0);
            _unitOfWork.Save();
            TempData["Success"] = "Booking Cancelled Successfull";
            return RedirectToAction(nameof(BookingDetails), new { bookingId = booking.Id });
        }
        private List<int>  AssignAvailableVillaNumberByVilla(int villaId)
        {
            List<int> availableVillaNumbers = new();

            var villaNumbers=_unitOfWork.VillaNumber.GetAll(u=>u.VillaId==villaId);
            var checkedInVilla = _unitOfWork.Booking.GetAll(u => u.VillaId == villaId && u.Status == SD.StatusCheckedIn).Select(u => u.VillaNumber);

            foreach(var villaNumber in villaNumbers)
            {
                if(!checkedInVilla.Contains(villaNumber.Villa_Number))
                {
                    availableVillaNumbers.Add(villaNumber.Villa_Number);
                }
            }
            return availableVillaNumbers;
        }



        #region API Calls
        [HttpGet]
        [Authorize]
        public IActionResult GetAll(string status)
        {
            IEnumerable<Booking> objBookings;

            if(User.IsInRole(SD.Role_Admin))
            {
                objBookings=_unitOfWork.Booking.GetAll(includeProperties:"User,Villa");
            }
            else
            {
                var claimsIdentity= (ClaimsIdentity)User.Identity;
                var userId=claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;

                objBookings = _unitOfWork.Booking.GetAll(u => u.UserId == userId, includeProperties: "User,Villa");
            }
            if(!string.IsNullOrEmpty(status))
            {
                objBookings= objBookings.Where(x => x.Status.ToLower().Equals(status.ToLower()));
            }
           
            return Json(new {data=objBookings});
        }
        #endregion
    }
}

Green_Lagoon/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;

namespace Green_Lagoon.Controllers
{
    public class DashboardController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Green_Lagoon/Controllers/VillaController.cs
using Green_Lagoon.Application.Common.Interface;
using Green_Lagoon.Domain.Entities;
using Green_Lagoon.Infrastructure.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Green_Lagoon.Controllers
{
    [Authorize]
    public class VillaController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public VillaController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _webHostEnvironment = webHostEnvironment;
        } 
        public IActionResult Index()
        {
            var villas= _unitOfWork.Villa.GetAll();
            return View(villas);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Villa obj)
        {
            if(obj.Name==obj.Description)
            {
                ModelState.AddModelError("name", "Name and Description must not be the same.");
            }
            if(ModelState.IsValid)
            {
                if(obj.Image != null)
                {
                    string filename= Guid.NewGuid().ToString() + Path.GetExtension(obj.Image.FileName);
                    string imagePath = Path.Combine(_webHostEnvironment.WebRootPath,@"images\VillaImage");

                    using var fileStream = new FileStream(Path.Combine(imagePath, filename), FileMode.Create);
                    obj.Image.CopyTo(fileStream);

                    obj.ImageUrl=@"\images\VillaImage\"+filename;
                }
                else
                {
                    obj.ImageUrl = "https://placehold.co/600x402";
                }
                _unitOfWork.Villa.Add(obj);
                _unitOfWork.Save();
                TempData["success"] = "The Villa has been created successfully.";
                return RedirectToAction(nameof(Index));
            }
            TempData["error"] = "The Villa can not be created.";
            return View();
            
        }
        [HttpGet]
        public IActionResult Update(int villaid)
        {
            Villa? obj= _unitOfWork.Villa.Get(x => x.Id==villaid);
            if(obj==null) 
            { 
               return RedirectToAction("Error","Home");
            }
            return View(obj);
        }
        [HttpPost]
        public IActionResult Update(Villa obj)
        {
           
            if (ModelState.IsValid)
            {
                if (obj.Image != null)
                {
                    string filename = Guid.NewGuid().ToString() + Path.GetExtension(obj.Image.FileName);
                    string imagePath = Path.Combine(_webHostEnvironment.WebRootPath, @"images\VillaImage");

                    if(!string.IsNullOrEmpty(obj.ImageUrl))
                    {
                        var oldImagePath = Path.Combine(_webHostEnvironment.WebRootPath, obj.ImageUrl.TrimStart('\\'));
                        if(System.IO.File.Exists(oldImagePath))
                        {
                            System.IO.File.Delete(oldImagePath);
                        }
                    }
                    using var fileStream = new FileStream(Path.Combine(imagePath, filename), FileMode.Create);
                    obj.Image.CopyTo(fileStream);

                    obj.ImageUrl = @"\images\VillaImage\" + filename;
                }
                
                _unitOfWork.Villa.Update(obj);
                _unitOfWork.Save();
                TempData["success"] = "The Villa has been updated successfully.";
                return RedirectToAction(nameof(Index));
            }
            TempData["error"] = "The Villa can not be updated.";
            return View();

        }
        [HttpGet]
        public IActionResult Delete(int villaid)
        {
            Villa? obj = _unitOfWork.Villa.Get(x => x.Id == villaid);
            if (obj is null)
            {
                return RedirectToAction("Error", "Home");
            }
            return View(obj);
        }
        [HttpPost]
        public IActionResult Delete(Villa obj)
        {
            Villa? objfromDb = _unitOfWork.Villa.Get(x=>x.Id==obj.Id);
            if(objfromDb is not null)
            {
                if (!string.IsNullOrEmpty(objfromDb.ImageUrl))
                {
                    var oldImagePath = Path.Combine(_webHostEnvironment.WebRootPath, objfromDb.ImageUrl.TrimStart('\\'));
                    if (System.IO.File.Exists(oldImagePath))
                    {
                        System.IO.File.Delete(oldImagePath);
                    }
                }
                _unitOfWork.Villa.Remove(objfromDb);
                _unitOfWork.Save();
                TempData["success"] = "The Villa has been deleted successfully.";
                return RedirectToAction(nameof(Index));

            }
            TempData["error"] = "The Villa can not be deleted.";

            return View();

        }

    }
}

Green_Lagoon/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Green_Lagoon</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.2/css/bootstrap.min.css" integrity="sha512-b2QcS5SsA8tZodcDtGRELiGv5SaKSk1vDHDaQRda0htPYWZ6046lr3kJ5bAAQdpV2mmA/4v0wQF9MyU6/pDIAg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.2/font/bootstrap-icons.min.css"
    <link rel="stylesheet" href="~/Green_Lagoon.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.css" integrity="sha512-3pIirOrwegjM6erE5gPSwkUzO+3cTjpnV9lexlNZqvupR64iZBnOOTiiLPb9M36zpMScbmUNIcHUqKD47M719g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/css/Spinner.css" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light  border-bottom box-shadow ">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/images/resort.png" style="width:35px" /></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (User.IsInRole(SD.Role_Admin))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Content Management
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li>
                                        <a class="dropdown-item" asp-area="" asp-controller="Villa" asp-action="Index">Villas</a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item" asp-area="" asp-controller="VillaNumber" asp-action="Index">VillaNumber</a>
                                    </li>
                                    <li><hr class="dropdown-divider"></li>
                                    <li>
                                        <a class="dropdown-item" asp-area="" asp-controller="VillaAmenity" asp-action="Index">Amenities</a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item" asp-area="" asp-controller="Booking" asp-action="Index" asp-route-status="@SD.StatusApproved">Bookings</a>
                                    </li>
                                </ul>
                            </li>
                        }
                        else
                        {
                            <li>
                                <a class="nav-link"  asp-controller="Booking" asp-action="Index" > Manage Bookings</a>
                            </li>
                        }

                       
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="">
        <main role="main" class="">
            <div class="loading spinner" style="display:none"></div>
            <partial name="_Notifications" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer bg-dark text-muted">
        <div class="container text-center">
            Made with <i class="bi bi-heart-fill"></i> by Sbongakonke_Sithole
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.2/js/bootstrap.min.js" integrity="sha512-WW8/jxkELe2CAiE4LvQfwm1rajOS8PHasCCx+knHG0gBHt8EXxS6T6tJRTGuDQVnluuAvMxWF4j8SNFDKceLFg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.0.1/js/bootstrap.bundle.min.js" integrity="sha512-sH8JPhKJUeA9PWk3eOcOl8U+lfZTgtBXD41q6cO/slwxGHCxKcW45K4oPCUhHG7NMB4mbKEddVmPuTXtpbCbFA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.datatables.net/1.13.7/js/jquery.dataTables.min.js" asp-append-version="true"></script>
   @*  <script src="~/js/jquery.unobtrusive-ajax.min.js"></script> *@
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Green_Lagoon/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Green_Lagoon</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.2/css/bootstrap.min.css" integrity="sha512-b2QcS5SsA8tZodcDtGRELiGv5SaKSk1vDHDaQRda0htPYWZ6046lr3kJ5bAAQdpV2mmA/4v0wQF9MyU6/pDIAg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.2/font/bootstrap-icons.min.css"
    <link rel="stylesheet" href="~/Green_Lagoon.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.css" integrity="sha512-3pIirOrwegjM6erE5gPSwkUzO+3cTjpnV9lexlNZqvupR64iZBnOOTiiLPb9M36zpMScbmUNIcHUqKD47M719g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/css/Spinner.css" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light  border-bottom box-shadow ">
            <div class="container-fluid d-flex justify-content-between">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/images/resort.png" style="width:35px" /></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
            <partial name="_LoginPartialAdmin" />
        </nav>
    </header>
    <div class="container-fluid">
        <div class="loading spinner" style="display:none"></div>
        <div class="row">
            <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-dark sidebar collapse">
                <div class="position-sticky pt-3">
                    <ul class="navbar-nav">
                        <li class="text-muted small fn-bold text-uppercase px-3">Menu</li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Dashboard" asp-action="Index">
                                 <span class="me-2">
                                     <i class="bi bi-speedometer2">
                                            <span>Dashboard</span>
                                     </i>
                                 </span>
                                
                            </a>
                        </li>
                        <li class="text-muted small fn-bold text-uppercase px-3"> Content Management</li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Villa" asp-action="Index">
                                <span class="me-2">
                                    <i class="bi bi-house-door">
                                        <span>Villas</span>
                                    </i>
                                </span>

                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="VillaNumber" asp-action="Index">
                                <span class="me-2">
                                    <i class="bi bi-list-ol">
                                        <span>VillaNumbers</span>
                                    </i>
                                </span>

                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="VillaAmenity" asp-action="Index">
                                <span class="me-2">
                                    <i class="bi bi-building">
                                        <span>Amenity</span>
                                    </i>
                                </span>

                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Booking" asp-action="Index" asp-action="Index" asp-route-status="@SD.StatusApproved">
                                <span class="me-2">
                                    <i class="bi bi-journal-plus">
                                        <span>Bookings</span>
                                    </i>
                                </span>

                            </a>
                        </li>
                           
                   
        
                    </ul>
                </div>

            </nav>
            <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
                <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 w-100">
                    <partial name="_Notifications" />
                    @RenderBody()
                </div>
              
            </main>
        </div>
        
    </div>

    <footer class="border-top footer bg-dark text-muted">
        <div class="container text-center">
            Made with <i class="bi bi-heart-fill"></i> by Sbongakonke_Sithole
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.2/js/bootstrap.min.js" integrity="sha512-WW8/jxkELe2CAiE4LvQfwm1rajOS8PHasCCx+knHG0gBHt8EXxS6T6tJRTGuDQVnluuAvMxWF4j8SNFDKceLFg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.0.1/js/bootstrap.bundle.min.js" integrity="sha512-sH8JPhKJUeA9PWk3eOcOl8U+lfZTgtBXD41q6cO/slwxGHCxKcW45K4oPCUhHG7NMB4mbKEddVmPuTXtpbCbFA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.datatables.net/1.13.7/js/jquery.dataTables.min.js" asp-append-version="true"></script>
   @*  <script src="~/js/jquery.unobtrusive-ajax.min.js"></script> *@
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Green_Lagoon/Views/Shared/_LoginPartialAdmin.cshtml
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

<ul class="navbar-nav d-none d-md-flex nav-login">
   <li class="nav-item dropdown">
        <a class="nav-link" href="#"
           id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
           @UserManager.GetUserName(User)
        </a>
        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="nav-link text-center" asp-controller="Account" asp-action="Logout">Logout</a>
        </ul>
   </li>

</ul>

Green_Lagoon/Views/Shared/_VillaList.cshtml
@model HomeViewModel

<div id="VillasList">
    <div class="row px-lg-5 m-lg-4 m-sm-0 px-sm-0" style="--bs-gutter-x:0">

        @foreach (var villa in Model.VillaList)
        {
            <div class="p-4 col-md-12 col-lg-6">
                <div class="row" style="border-radius:5px; border: 1px solid #aaa">
                    <div class="col-4 p-2">
                        <img class="d-block w-100" style="border-radius:5px;" src="@villa.ImageUrl">
                    </div>
                    <div class="col-8">
                        <div class="d-flex justify-content-between">
                            <p class="card-title text-warning" style="font-size:xx-large">@villa.Name</p>
                            <div class="pt-2">
                                <button type="button" class="btn btn-sm btn-outline-success" data-bs-toggle="modal" data-bs-target='#exampleModal-@(villa.Id)'>
                                    Details
                                </button>
                            </div>
                        </div>
                        <p class="card-text">
                            @Html.Raw(villa.Description)

                        </p>
                    </div>
                    <div class="col-12">
                        <div class="row pb-3 pt-2">
                            <div class="col-4">
                                @if (Model.CheckInDate > DateOnly.FromDateTime(DateTime.Now))
                                {
                                    if (villa.IsAvailable)
                                    {
                                        <a asp-controller="Booking" asp-action="FinalizeBooking" asp-route-villaId="@villa.Id" asp-route-checkInDate="@Model.CheckInDate" asp-route-nights="@Model.Nights" class="btn btn-success form-control btn-block">
                                            Book
                                        </a>
                                    }
                                    else
                                    {
                                        <a class="btn btn-outline-danger disabled form-control btn-block">
                                            Fully Booked
                                        </a>
                                    }

                                }

                            </div>
                            <div class="col-4">
                                <span class="">Max Occupancy : @villa.Occupancy adults </span><br />
                                <span class=" pt-1">Villa Size : @villa.Sqft sqft</span><br />
                            </div>
                            <div class="col-4">
                                <span class="text-warning float-end font-weight-bold pt-1" style="font-size:25px;">
                                    USD
                                    <span style="border-bottom:1px solid #ff6a00">
                                        @villa.Price.ToString("c")
                                    </span>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>


            <div class="modal fade" id="exampleModal-@(villa.Id)" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog modal-xl" style="border: 1px solid #aaa; border-radius:7px;">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h1 class="modal-title fs-3 text-success" id="exampleModalLabel">Villa Details </h1>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body m-0">

                            <partial name="_VillaDetail" model="@villa" />
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-outline-danger" data-bs-dismiss="modal">Close</button>
                        </div>

                    </div>
                </div>
            </div>

        }

    </div>
</div>