Green_Lagoon/ViewModels/VillaNumberViewModel.cs
using Green_Lagoon.Domain.Entities;
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Green_Lagoon.ViewModels
{
    public class VillaNumberViewModel
    {
        public VillaNumber VillaNumber { get; set; }
        [ValidateNever]
        public IEnumerable<SelectListItem> VillaList { get; set; }
    }
}

Green_Lagoon/Controllers/VillaNumberController.cs
using Green_Lagoon.Application.Common.Interface;
using Green_Lagoon.Domain.Entities;
using Green_Lagoon.Infrastructure.Data;
using Green_Lagoon.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Green_Lagoon.Controllers
{
    public class VillaNumberController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public VillaNumberController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            var villaNumbers = _unitOfWork.VillaNumber.GetAll(includeProperties: "Villa");
            return View(villaNumbers);
        }
        public IActionResult Create()
        {
            VillaNumberViewModel villaNumber = new()
            {
                VillaList = _unitOfWork.Villa.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString(),
                })
            };


            return View(villaNumber);
        }
        [HttpPost]
        public IActionResult Create(VillaNumberViewModel obj)
        {
            bool roomNumberExists = _unitOfWork.VillaNumber.Any(u => u.Villa_Number == obj.VillaNumber.Villa_Number);

            if (ModelState.IsValid && !roomNumberExists)
            {
                _unitOfWork.VillaNumber.Add(obj.VillaNumber);
                _unitOfWork.Save();
                TempData["success"] = "The Villa Number has been created successfully.";
                return RedirectToAction(nameof(Index));
            }
            if (roomNumberExists)
            {
                TempData["error"] = "The Villa Number already exists";
            }
            obj.VillaList = _unitOfWork.Villa.GetAll().Select(u => new SelectListItem
            {
                Text = u.Name,
                Value = u.Id.ToString(),
            });
            return View(obj);

        }
        [HttpGet]
        public IActionResult Update(int villaNumberId)
        {
            VillaNumberViewModel villaNumberVM = new()
            {
                VillaList = _unitOfWork.Villa.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString(),
                }),
                VillaNumber = _unitOfWork.VillaNumber.Get(u => u.Villa_Number == villaNumberId)
            };

            if (villaNumberVM.VillaNumber == null)
            {
                return RedirectToAction("Error", "Home");
            }
            return View(villaNumberVM);
        }
        [HttpPost]
        public IActionResult Update(VillaNumberViewModel villaNumberViewModel)
        {


            ModelState.Remove("VillaList");
            if (ModelState.IsValid)
            {
                _unitOfWork.VillaNumber.Update(villaNumberViewModel.VillaNumber);
                _unitOfWork.Save();
                TempData["success"] = "The Villa Number has been updated successfully.";
                return RedirectToAction(nameof(Index));
            }


            villaNumberViewModel.VillaList = _unitOfWork.Villa.GetAll().Select(u => new SelectListItem
            {
                Text = u.Name,
                Value = u.Id.ToString(),
            });
            return View(villaNumberViewModel);

        }
        [HttpGet]
        public IActionResult Delete(int villaNumberId)
        {
            VillaNumberViewModel villaNumberVM = new()
            {
                VillaList = _unitOfWork.Villa.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString(),
                }),
                VillaNumber = _unitOfWork.VillaNumber.Get(u => u.Villa_Number == villaNumberId)
            };

            if (villaNumberVM.VillaNumber == null)
            {
                return RedirectToAction("Error", "Home");
            }
            return View(villaNumberVM);
        }
        [HttpPost]
        public IActionResult Delete(VillaNumberViewModel villaNumberViewModel)
        {
            VillaNumber? objfromDb = _unitOfWork.VillaNumber.Get(x => x.Villa_Number == villaNumberViewModel.VillaNumber.Villa_Number);
            if (objfromDb is not null)
            {
                _unitOfWork.VillaNumber.Remove(objfromDb);
                _unitOfWork.Save();
                TempData["success"] = "The Villa Number has been deleted successfully.";
                return RedirectToAction(nameof(Index));

            }
            TempData["error"] = "The Villa Number can not be deleted.";

            return View();

        }

    }
}

Green_Lagoon/Views/VillaNumber/Create.cshtml
@model VillaNumber

<div class="w-100 card border-0">
    <div class="card-header bg-success bg-gradient m-lg-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h1 class="text-white py-2">Create Villa Number</h1>
            </div>
        </div>
    </div>
</div>
<div class="card-body border-4">
    <form method="post" class="row">
        <div class="p-3">
            @*  <div asp-validation-summary="ModelOnly"></div> *@
            <div class="form-floating py-2 col-12">
               <select asp-for="@Model.VillaId" asp-items="@ViewData["VillaList"] as IEnumerable<SelectListItem>" class="form-select border shadow">
                   <option disabled selected>--Select Villa--</option>
               </select>
                <label asp-for="VillaId" class="ms-2"></label>
               
            </div>
            <div class="form-floating py-2 col-12">
                <input asp-for="@Model.Villa_Number" class="form-control border shadow" />
                <label asp-for="Villa_Number" class="ms-2"></label>
                
            </div>
            <div class="form-floating py-2 col-12">
                <input asp-for="@Model.SpecialDetails" class="form-control border shadow" />
                <label asp-for="SpecialDetails" class="ms-2"></label>
               
            </div>
            <div class="row pt-2">
                <div class="col-6 col-md-3">
                    <button type="submit" class="btn btn-success w-100">
                        <i class="bi bi-check-circle"> Create</i>
                    </button>
                </div>
                <div class="col-6 col-md-3">
                    <a asp-controller="VillaNumber" asp-action="Index" class="btn btn-secondary w-100">
                        <i class="bi bi-x-circle"> Cancel</i>
                    </a>
                </div>
            </div>
        </div>
    </form>

</div>

@* @section Scripts{
    @{
        <partial name="_ValidationScripsPartial" />
    }
} *@

Green_Lagoon/Views/VillaNumber/Delete.cshtml
@model VillaNumberViewModel

<div class="w-100 card border-0">
    <div class="card-header bg-success bg-gradient m-lg-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h1 class="text-white py-2">Delet Villa Number</h1>
            </div>
        </div>
    </div>
</div>
<div class="card-body border-4">
    <form method="post" class="row">

        <input asp-for="VillaNumber.Villa_Number" hidden />
        <div class="p-3">

            <div class="form-floating py-2 col-12">
                <select asp-for="@Model.VillaNumber.VillaId" disabled asp-items="@Model.VillaList" class="form-select border shadow">
                    <option disabled selected>--Select Villa--</option>
                </select>
                <label asp-for="VillaNumber.VillaId" class="ms-2"></label>

            </div>
            <div class="form-floating py-2 col-12">
                <input asp-for="@Model.VillaNumber.Villa_Number" disabled class="form-control border shadow" />
                <label asp-for="VillaNumber.Villa_Number" class="ms-2"></label>

            </div>
            <div class="form-floating py-2 col-12">
                <input asp-for="@Model.VillaNumber.SpecialDetails" disabled class="form-control border shadow" />
                <label asp-for="VillaNumber.SpecialDetails" class="ms-2"></label>

            </div>
            <div class="row pt-2">
                <div class="col-6 col-md-3">
                    <button type="submit" class="btn btn-danger w-100">
                        <i class="bi bi-check-circle"> Delete</i>
                    </button>
                </div>
                <div class="col-6 col-md-3">
                    <a asp-controller="VillaNumber" asp-action="Index" class="btn btn-secondary w-100">
                        <i class="bi bi-x-circle"> Cancel</i>
                    </a>
                </div>
            </div>
        </div>
    </form>

</div>

@* @section Scripts{
    @{
        <partial name="_ValidationScripsPartial" />
    }
} *@

Green_Lagoon/Views/VillaNumber/Index.cshtml
@model IEnumerable<VillaNumber>

<div class="w-100 card border-0">
    <div class="card-header bg-success bg-gradient m-lg-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h1 class="text-white py-2">Villa Number List</h1>
            </div>
        </div>
    </div>
    <div class="card-body border p-4">
        <div class="row pb-3">
            <div class="col-6 offset-6 text-end">
                <a asp-controller="VillaNumber" asp-action="Create" class="btn btn-secondary">
                    <i class="bi bi-plus-circle"></i> Create New Villa Number
                </a>
            </div>
        </div>
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>
                        Villa Name
                    </th>
                    <th>
                        Villa Number
                    </th>
                    <th>
                        Special Details
                    </th>
                    
                    <th>

                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var obj in Model)
                {
                    <tr>
                        <td>
                            @obj.Villa.Name
                        </td>
                        <td>
                            @obj.Villa_Number
                        </td>
                        <td>
                            @obj.SpecialDetails
                        </td>
                       
                        <td>
                            <div class="w-75 btn-group" role="group">
                                <a asp-controller="VillaNumber" asp-action="Update" asp-route-villaNumberId="@obj.Villa_Number" class="btn btn-success mx-2">
                                    <i class="bi bi-pencil-square">Edit</i>
                                </a>
                                <a asp-controller="VillaNumber" asp-action="Delete" asp-route-villaNumberId="@obj.Villa_Number" class="btn btn-danger mx-2">
                                    <i class="bi bi-trash-fill">Delete</i>
                                </a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

Green_Lagoon/Views/VillaNumber/Update.cshtml
@model VillaNumberViewModel

<div class="w-100 card border-0">
    <div class="card-header bg-success bg-gradient m-lg-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h1 class="text-white py-2">Update Villa Number</h1>
            </div>
        </div>
    </div>
</div>
<div class="card-body border-4">
    <form method="post" class="row">
        <div class="p-3">

            <div class="form-floating py-2 col-12">
                <select asp-for="@Model.VillaNumber.VillaId" asp-items="@Model.VillaList" class="form-select border shadow">
                    <option disabled selected>--Select Villa--</option>
                </select>
                <label asp-for="VillaNumber.VillaId" class="ms-2"></label>

            </div>
            <div class="form-floating py-2 col-12">
                <input asp-for="@Model.VillaNumber.Villa_Number" class="form-control border shadow" />
                <label asp-for="VillaNumber.Villa_Number" class="ms-2"></label>

            </div>
            <div class="form-floating py-2 col-12">
                <input asp-for="@Model.VillaNumber.SpecialDetails" class="form-control border shadow" />
                <label asp-for="VillaNumber.SpecialDetails" class="ms-2"></label>

            </div>
            <div class="row pt-2">
                <div class="col-6 col-md-3">
                    <button type="submit" class="btn btn-success w-100">
                        <i class="bi bi-check-circle"> Update</i>
                    </button>
                </div>
                <div class="col-6 col-md-3">
                    <a asp-controller="VillaNumber" asp-action="Index" class="btn btn-secondary w-100">
                        <i class="bi bi-x-circle"> Cancel</i>
                    </a>
                </div>
            </div>
        </div>
    </form>

</div>

@* @section Scripts{
    @{
        <partial name="_ValidationScripsPartial" />
    }
} *@